### ISSUE TITLE
NameError: name 'gt' is not defined in PLS Discriminant Analysis for binary classification in Python

### ISSUE THREAD

**Issue by zwitter689** [nevernervous78/nirpyresearch#3]
First let me say I greatly appreciate the tutorials you make available on NIRPY.
In the tutorial for PLS Discriminant Analysis for binary classification in Python
you define the function pls_da, it includes binary_prediction = (pls_binary.predict(X_test)[:,0] &gt; 0.5).astype('uint8'); which should have &gt, I'm guessing. The function definition  for def pls_da(X_train,y_train, X_test): is below
=============================================================
def pls_da(X_train,y_train, X_test): 
    # Define the PLS object for binary classification
    plsda = PLSRegression(n_components=2) 
    # Fit the training set
    plsda.fit(X_train, y_train)
    # Binary prediction on the test set, done with thresholding
    binary_prediction = (pls_binary.predict(X_test)[:,0] &gt; 0.5).astype('uint8')
    return binary_prediction
=============================================================
This is followed by code to do  K-Fold cross-validation with 10 splits and iterate through it. 
==================================================
accuracy = []
cval = KFold(n_splits=10, shuffle=True, random_state=19)
for train, test in cval.split(X_binary):    
    y_pred = pls_da(X_binary[train,:], y_binary[train], X_binary[test,:])    
    accuracy.append(accuracy_score(y_binary[test], y_pred)) 
print("Average accuracy on 10 splits: ", np.array(accuracy).mean
================================================
I run all the code you provide in a Jupyter notebook an when I run the next cell shown here I get 
..........................................................................................................................
--> 10     binary_prediction = (pls_binary.predict(X_test)[:,0] &gt, 0.5).astype('uint8')
     11 
     12     return binary_prediction

NameError: name 'gt' is not defined

So what is gt supposed tobe and where do I specify it?

**Comment by nevernervous78** [comment]
Thanks for alerting me about this problem.
Line 10 should read
binary_prediction = (pls_binary.predict(X_test)[:,0] > 0.5).astype('uint8')

The symbol ">" was somehow rendered incorrectly on the website. I have fixed it now.

**Comment by zwitter689** [comment]
You're more than welcome.
Marty
***@***.***)
Light travels faster than sound,  and so, some people appear bright until
you hear them speak.
